# File: docker-compose.yml
# This file is a merged version of docker-compose.yml, docker-compose.override.yml,
# and docker-compose.traefik.yml.

services:
  db:
    image: ${DB_VERSION:-mariadb:11.8}
    env_file:
      - .env
    container_name: "pkp_db_${COMPOSE_PROJECT_NAME:-demo}"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-changeMePlease}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-pkp}"
      MYSQL_USER: "${MYSQL_USER:-pkp}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-changeMePlease}"
    volumes:
      - ./volumes/db:/var/lib/mysql
      - ./volumes/logs/db:/var/log/mysql
      - ./volumes/config/db.charset.conf:/etc/mysql/conf.d/charset.cnf
      - ./volumes/db-import:/docker-entrypoint-initdb.d
    networks:
      - inside
    restart: unless-stopped

  app:
    image: ${IMAGE_SOURCE:-local}/${PKP_TOOL:-omp}:${PKP_VERSION:-3_3_0-20}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PKP_TOOL: ${PKP_TOOL:-omp}
        PKP_VERSION: ${PKP_VERSION}
        WEB_SERVER: ${WEB_SERVER}
        BUILD_PKP_APP_OS: ${BUILD_PKP_APP_OS}
    env_file:
      - .env
    container_name: "pkp_app_${COMPOSE_PROJECT_NAME:-demo}"
    hostname: "${COMPOSE_PROJECT_NAME:-demo}"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./volumes/private:/var/www/files
      - ./volumes/public:/var/www/html/public
      - ./volumes/logs/app:/var/log/apache2
      - ./volumes/config/pkp.config.inc.php:/var/www/html/config.inc.php
      - ./volumes/config/apache.htaccess:/var/www/html/.htaccess
      - ./volumes/config/apache.servername.conf:/etc/apache2/conf-enabled/servername.conf
      - ./volumes/config/php.custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - proxy
      - inside
    depends_on:
      - db
    restart: unless-stopped
    ports: []
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.app.loadbalancer.server.port=80"

  traefik:
    image: traefik:v2.11
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080" # For Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./volumes/traefik/dynamic:/etc/traefik/dynamic:ro"
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
  inside:
    external: false