# File: docker-compose.override.yml
# Author: Marc Bria UAB (marc.bria@uab.es)

services:
  app:
    # When running behind Traefik, the app container should not publish its ports directly.
    # Traefik handles external traffic on ports 80 and 443 and routes it to the app container
    # over the internal 'proxy' network. We override the ports section with an empty list.
    ports: []
    labels:
      # Enable Traefik for this service.
      - "traefik.enable=true"
      # Explicitly tell Traefik to use the 'proxy' network to communicate with this service.
      # This is necessary because the 'app' container is attached to multiple networks.
      - "traefik.docker.network=proxy"
  
    networks:
      - proxy

networks:
  proxy:
    external: true
